const express = require('express')
const country = require('../api/country/country.router')
const state = require('../api/state/state.router')
const city = require('../api/city/city.router')
const address = require('../api/address/address.router')
const occupation = require('../api/occupation/occupation.router')
const employee = require('../api/employee/employee.router')
const customer = require('../api/customer/customer.router')
const supplier = require('../api/supplier/supplier.router')
const table = require('../api/table/table.router')
const productGroup = require('../api/product_group/product_group.router')
const unity = require('../api/unity/unity.router')
const coin = require('../api/coin/coin.router')
const quotation = require('../api/quotation/quotation.router')
const product = require('../api/product/product.router')
const bank = require('../api/bank/bank.router')
const bankAccount = require('../api/bank_account/bank_account.router')
const paymentForm = require('../api/payment_type/payment_type.router')
const paymentCondition = require('../api/payment_condition/payment_condition.router')
const accountsPayables = require('../api/accounts_payables/accounts_payables.router')
const cashRegister = require('../api/cash_register/cash_register.router')
const waiterRequest = require('../api/waiter_request/waiter_request.router')
const unitMeasurement = require('../api/unit_measurement/unit_measurement.router')
const customerAccount = require('../api/customer_account/customer.account.router')
const closure = require('../api/closure/closure.router')
const typeDocument = require('../api/type_document/type.document.router')
const accountsReceivable = require('../api/accounts_receivables/accounts.receivables.router')
const installmentsPayables = require('../api/installment_payables/installment.payables.router')
const installmentsReceivables = require('../api/installment_receivables/installment.receivables.router')
const menuGroup = require('../api/menu_group/menu.group.router')
const storage = require('../api/storage/storage.router')

const router = express.Router()

router.get('/', (req, res) => {
	res.status(200).json('Aplicação Rest Controller iniciada com sucesso.')
})

router.use('/paises', country)
router.use('/estados', state)
router.use('/cidades', city)
router.use('/enderecos', address)
router.use('/funcoes', occupation)
router.use('/funcionarios', employee)
router.use('/clientes', customer)
router.use('/fornecedores', supplier)
router.use('/mesas', table)
router.use('/grupos-produto', productGroup)
router.use('/unidades', unity)
router.use('/moedas', coin)
router.use('/cotacoes', quotation)
router.use('/produtos', product)
router.use('/bancos', bank)
router.use('/contas-bancarias', bankAccount)
router.use('/formas-pagamento', paymentForm)
router.use('/condicoes-pagamento', paymentCondition)
router.use('/contas-a-pagar', accountsPayables)
router.use('/caixa', cashRegister)
router.use('/pedidos', waiterRequest)
router.use('/unidade-medida', unitMeasurement)
router.use('/conta-cliente', customerAccount)
router.use('/fechamento', closure)
router.use('/tipo-documento', typeDocument)
router.use('/contas-a-receber', accountsReceivable)
router.use('/parcelas-a-pagar', installmentsPayables)
router.use('/parcelas-a-receber', installmentsReceivables)
router.use('/grupos-cardapio', menuGroup)
router.use('/estoque', storage)

module.exports = router
 