const express = require('express')
const country = require('../api/country/country.router')
const state = require('../api/state/state.router')
const city = require('../api/city/city.router')
const address = require('../api/address/address.router')
const occupation = require('../api/occupation/occupation.router')
const employee = require('../api/employee/employee.router')
const customer = require('../api/customer/customer.router')
const supplier = require('../api/supplier/supplier.router')
const table = require('../api/table/table.router')
const productGroup = require('../api/product_group/product_group.router')
const unity = require('../api/unity/unity.router')
const coin = require('../api/coin/coin.router')
const quotation = require('../api/quotation/quotation.router')
const product = require('../api/product/product.router')
const bank = require('../api/bank/bank.router')
const bankAccount = require('../api/bank_account/bank_account.router')
const paymentForm = require('../api/payment_type/payment_type.router')
const paymentCondition = require('../api/payment_condition/payment_condition.router')
const accountsPayables = require('../api/accounts_payables/accounts_payables.router')

const router = express.Router()

router.get('/', (req, res) => {
	res.status(200).json('Aplicação Rest Controller iniciada com sucesso.')
})

router.use('/paises', country)
router.use('/estados', state)
router.use('/cidades', city)
router.use('/enderecos', address)
router.use('/funcoes', occupation)
router.use('/funcionarios', employee)
router.use('/clientes', customer)
router.use('/fornecedores', supplier)
router.use('/mesas', table)
router.use('/grupos-produto', productGroup)
router.use('/unidades', unity)
router.use('/moedas', coin)
router.use('/cotacoes', quotation)
router.use('/produtos', product)
router.use('/bancos', bank)
router.use('/contas-bancarias', bankAccount)
router.use('/formas-pagamento', paymentForm)
router.use('/condicoes-pagamento', paymentCondition)
router.use('/contas-a-pagar', accountsPayables)

module.exports = router
