const HIDDEN_BIG_RETURN = 'OCULTADO_EM_FUNCAO_DO_TAMANHO'

/* REGEX */
const REGEX_TRIM_WHITESPACES_FROM_BEGGINING_AND_END = /^[ \t]+|[ \t]+$/g

const REGEX_DATE_FORMAT_YYYY_MM_DD = /[12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])?/g

const REGEX_KEEP_ONLY_NUMBERS = /[^0-9]/g

module.exports = {
	HIDDEN_BIG_RETURN,
  REGEX_TRIM_WHITESPACES_FROM_BEGGINING_AND_END,
	REGEX_DATE_FORMAT_YYYY_MM_DD,
	REGEX_KEEP_ONLY_NUMBERS
}