const HIDDEN_BIG_RETURN = 'OCULTADO_EM_FUNCAO_DO_TAMANHO'

const REGEX_TRIM_WHITESPACES_FROM_BEGGINING_AND_END = /^[ \t]+|[ \t]+$/g

module.exports = {
	HIDDEN_BIG_RETURN,
  REGEX_TRIM_WHITESPACES_FROM_BEGGINING_AND_END
}